---
title: "Lecture Slide Status Overview"
date: '`r format(Sys.time(), format = "%F %T", tz = "Europe/Berlin", usetz = TRUE)`'
output: 
  github_document:
    toc: true
    toc_depth: 3
always_allow_html: true
editor_options:
  chunk_output_type: console
---

This is a reduced version of the full status check rendered for each lecture repository.  
It does not link to rendered PDF files and only produces markdown tables, which allows it to be appended to a pull request.
It serves as a rough check to ensure that the PR does not cause major breakage.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(lese)
library(dplyr)
library(knitr)

included_lectures <- lectures()

if (!file.exists("slide_check_cache.rds")) {
  stop(paste(
    "slide_check_cache.rds does not exists.",
    "Run `make` and get a coffee, or",
    "Rscript -e 'lese::check_slides_many()", sep = "\n "
  ))
}

all_slide_check <- readRDS("slide_check_cache.rds")

# Get lectures and reorder them
# Ignores lectures that exist locally but are not listed in included_lectures
lectures <- unique(all_slide_check$lecture)
lectures <- lectures[match(included_lectures, lectures, nomatch = 0)]

# Might as well subset table to only selected lectures
# This allows having a lecture locally for testing but not include them here yet.
all_slide_check <- all_slide_check[all_slide_check$lecture %in% included_lectures, ]
```

```{r slide-checker-repo-status}
this_repo_status() |>
  mutate(
    branch = sprintf("<a href='https://github.com/slds-lmu/lecture_service/tree/%s'>%s</a>", branch, branch)
  ) |>
  select(branch, last_commit_time, last_commit_by, last_commit_summary) |>
  kable(
    col.names = c("Branch", "Last Commit", "By", "Message"),
    escape = FALSE, caption = "Status of the lecture_service repo (time in UTC)"
  )
```


```{r lecture-repo-status}
lecture_status_local(lectures) |>
  arrange(desc(last_commit_time)) |>
  mutate(
    lecture_link = sprintf("<a href='https://%s.github.io/%s'>%s</a>", org, lecture, lecture),
    branch = sprintf("<a href='https://github.com/%s/%s/tree/%s'>%s</a>", org, lecture, branch, branch)
  ) |>
  select(lecture_link, branch, last_commit_time, last_commit_by, last_commit_summary) |>
  kable(
    col.names = c("Lecture", "Branch", "Last Commit", "By", "Message"),
    escape = FALSE, caption = "Latest commits per lecture (times in UTC)"
  )
```


```{r data-prep, include=FALSE}
check_table <- all_slide_check |>
  # Transforms the logical columns, i.e. pdf_exists, pdf_static_exists, compile_check, ...
  mutate(across(where(is.logical), \(x) {
    case_when(
      x ~ "\u2705",  # Green check symbol
      !x ~ "\u274c", # Red X symbol
      is.na(x) ~ ""
    )
  })) |>
  mutate(
    # Insert red question mark emoji instead of red X for easier visual parsing maybe
    compare_check = ifelse(grepl("Dissimilar pages", compare_check_note), "\u2753", compare_check),
    compare_check = ifelse(grepl("No reference", compare_check_note), "", compare_check)
  ) |>
  # Make links out of a few columns
  mutate(
    comparison_path = here::here("comparison", fs::path_file(pdf)),
    check_note = compare_check_note,
    compile_note = stringr::str_replace_all(compile_note, "`", "'") |>
      stringr::str_replace_all(r"(\\)", r"(\\\\)"),
    check_note = ifelse(compile_check == "\u274c", compile_note, check_note)
  )


```


```{r  slide-status-table, results='asis'}
# This is a markdown "asis" chunk that can output raw markdown or HTML and is treated as such by knitr
# Useful to manually assemble tables with sub-headings

# Switch table properties depending on whether we have comparison checks or not
if (!all(check_table$compare_check == "")) {
  check_cols <- c("compile_check", "compare_check")
  col_align <- c("l", "c", "c", "l")
  col_names <- c("Slide", "Compiles?", "Comparison", "Note")
} else {
  check_cols <- c("compile_check")
  col_align <- c("l", "c", "l")
  col_names <- c("Slide", "Compiles?", "Note")
}

for (current_lecture in lectures) {

  tmp <- check_table |>
    filter(lecture == current_lecture)

  cat(sprintf("\n## %s \n\n", current_lecture))

  cat(sprintf("%i topics with a total of %i slides\n", length(unique(tmp$topic)), nrow(tmp)))
  
  tmp |>
    count(compile_check) |>
    kable(
      format = "html"
    ) |>
    cat()
  
  tmp |>
    count(across(any_of(check_columns))) |>
    kable(
      format = "html"
    ) |>
    cat()

  for (current_topic in sort(unique(tmp$topic))) {
    tmp <- check_table |>
      filter(lecture == current_lecture, topic == current_topic)

    cat(sprintf("\n### %s\n\n", current_topic))
    
    tmp |>
      select(
        slide_name, any_of(check_columns), check_note
      ) |>
      kable(
        # Needs to be HTML even for markdown output, tables don't render properly otherwise
        format = "html", 
        align = col_align,
        col.names = col_names
      ) |>
      cat()
  }
}
```
