#! /bin/bash

docker run \
  -p 8787:8787 \
  -e DISABLE_AUTH=true \
  --cpus=4 \
  jemus42/lecture_service:latest
#  -v $(pwd):/home/rstudio/work \

# docker run -it -v $(pwd):/home/rstudio/work -u rstudio jemus42/lecture_service:latest lecheck
